'use client';
import { useEffect, useState } from 'react';

function Logo() {
  return (
    <a href="/" className="v6-logo" aria-label="EnableOS">
      <svg viewBox="0 0 320 80" xmlns="http://www.w3.org/2000/svg" className="v6-logo-svg">
        <defs>
          <linearGradient id="logoG1" x1="0" y1="0" x2="1" y2="0"><stop offset="0%" stopColor="#BDA9FF"/><stop offset="100%" stopColor="#9B7EFF"/></linearGradient>
          <linearGradient id="logoG2" x1="0" y1="0" x2="1" y2="0"><stop offset="0%" stopColor="#9B7EFF"/><stop offset="100%" stopColor="#7C5CFC"/></linearGradient>
          <linearGradient id="logoG3" x1="0" y1="0" x2="1" y2="0"><stop offset="0%" stopColor="#7C5CFC"/><stop offset="100%" stopColor="#5B3EDB"/></linearGradient>
        </defs>
        <rect x="20" y="20" width="52" height="9" rx="2.5" fill="url(#logoG1)" opacity="0.55"/><rect x="26" y="35" width="52" height="12" rx="2.5" fill="url(#logoG2)" opacity="0.8"/><rect x="32" y="53" width="52" height="16" rx="2.5" fill="url(#logoG3)"/>
        <line x1="26" y1="35" x2="20" y2="29" stroke="#BDA9FF" strokeWidth="0.8" opacity="0.45"/><line x1="32" y1="53" x2="26" y2="47" stroke="#9B7EFF" strokeWidth="0.8" opacity="0.5"/><line x1="78" y1="35" x2="72" y2="29" stroke="#BDA9FF" strokeWidth="0.8" opacity="0.45"/><line x1="84" y1="53" x2="78" y2="47" stroke="#9B7EFF" strokeWidth="0.8" opacity="0.5"/>
        <circle cx="79" cy="61" r="3" fill="#ffffff" opacity="0.9"/><circle cx="70" cy="61" r="3" fill="#BDA9FF" opacity="0.7"/>
        <text x="102" y="68" fontFamily="'Libre Baskerville', Georgia, serif" fontSize="38" fontWeight="400" fill="currentColor" letterSpacing="-0.02em">Enable<tspan fontWeight="700" className="v6-logo-os">OS</tspan></text>
      </svg>
    </a>
  );
}

function FAQ() {
  const [open, setOpen] = useState(null);
  const faqs = [
    { q: 'How long until the workspace is ready?', a: 'Most workspaces are delivered within 4-6 weeks. Discovery in week 0, build in weeks 1-4, launch call in week 4-5.' },
    { q: 'Can reps log in too?', a: 'Yes. Every workspace supports multiple users. Reps see shared content and sessions. Coaching notes stay private.' },
    { q: 'What if we already have content and tools?', a: 'Even better. Existing playbooks, Gong recordings, and onboarding materials get audited, restructured, and migrated in.' },
    { q: 'What happens after 3 months?', a: 'Continue with monthly check-ins, switch to quarterly reviews, or run independently. The platform and data stay yours.' },
    { q: 'Is this just for SDR teams?', a: 'No. Works for any revenue team — SDRs, AEs, full-cycle reps. The workspace gets configured for the specific sales motion.' },
    { q: 'How is this different from Notion?', a: 'Notion stores content. EnableOS auto-prioritizes requests, tracks onboarding per rep, analyzes coaching notes with AI, and gives a live impact dashboard. And it arrives pre-built.' },
  ];
  return (<div className="v6-faq-list">{faqs.map((f, i) => (<div key={i} className="v6-faq-item" onClick={() => setOpen(open === i ? null : i)}><div className="v6-faq-q"><span>{f.q}</span><span className="v6-faq-toggle">{open === i ? '−' : '+'}</span></div>{open === i && <p className="v6-faq-a">{f.a}</p>}</div>))}</div>);
}

export default function Page() {
  useEffect(() => {
    function handleScroll() { const max = document.documentElement.scrollHeight - window.innerHeight; if (max <= 0) return; document.documentElement.style.setProperty('--p', Math.max(0, Math.min(1, window.scrollY / max)).toFixed(3)); }
    window.addEventListener('scroll', handleScroll, { passive: true }); handleScroll();
    return () => { window.removeEventListener('scroll', handleScroll); document.documentElement.style.removeProperty('--p'); };
  }, []);

  return (
    <>
      <style dangerouslySetInnerHTML={{ __html: styles }} />
      <div className="v6-wrap">
        <div className="v6-bg" aria-hidden="true">
          <div className="v6-aurora" />
          <div className="v6-dots" />
          <div className="v6-orb v6-orb-1" />
          <div className="v6-orb v6-orb-2" />
          <div className="v6-orb v6-orb-3" />
          <div className="v6-frag v6-frag-pri-1">P 21</div>
          <div className="v6-frag v6-frag-pri-2">P 15</div>
          <div className="v6-frag v6-frag-pri-3">P 18</div>
          <div className="v6-frag v6-frag-ai-1">🎯 Coach this week</div>
          <div className="v6-frag v6-frag-dot v6-frag-dot-1" />
          <div className="v6-frag v6-frag-dot v6-frag-dot-2" />
          <div className="v6-frag v6-frag-dot v6-frag-dot-3" />
        </div>
        <div className="v6-scroll-hint">Scroll ↓</div>
        <div className="v6-content">
          <nav className="v6-nav"><Logo /><div className="v6-navlinks"><a href="#how-it-works">How it works</a><a href="#who-its-for">Who it&apos;s for</a><a href="#faq">FAQ</a><a href="/consulting">Consulting</a><a href="/demo" className="v6-demo-link">Explore demo</a><a href="/login">Log in</a><a href="https://calendly.com/enableos-hq/30min" target="_blank" rel="noreferrer" className="v6-cta-nav">Book a call</a></div></nav>

          <section className="v6-section v6-hero"><div>
            <span className="v6-eyebrow">Sales enablement consulting + platform</span>
            <h1 className="v6-h1">Your reps ramp faster when someone <em>builds the system for you.</em></h1>
            <p className="v6-sub">We audit your sales process, design the systems, and hand you a workspace where everything&apos;s already live and tracking.</p>
            <div className="v6-btns"><a href="https://calendly.com/enableos-hq/30min" target="_blank" rel="noreferrer" className="v6-btn-p">Book a free discovery call →</a><a href="/demo" className="v6-btn-s">Explore the platform →</a></div>
            <div className="v6-hero-proof"><span>Enablement built at 2 B2B SaaS companies</span><span className="v6-sep">·</span><span>50% faster ramp</span><span className="v6-sep">·</span><span>20+ reps onboarded</span></div>
          </div><div className="v6-dash-wrap"><div className="v6-dash-glow" /><div className="v6-dash"><div className="v6-dh"><span>Your workspace · Live</span><span className="v6-dh-live"><span className="v6-dh-live-dot" />Ready</span></div><div className="v6-intake"><div className="v6-int-top"><div><div className="v6-int-title">Build battle card for Competitor X</div><div className="v6-int-meta">Auto-prioritized · High</div></div><span className="v6-pri">⬆ High</span></div></div><div className="v6-note"><div className="v6-note-rep">Rahul · 1:1 coaching note</div><div className="v6-note-txt">&quot;Pipeline feels slow this week...&quot;</div><span className="v6-ai">⚠ Confidence dropping — coach this week</span></div><div className="v6-ramp"><div className="v6-ramp-top"><span>Aisha · Onboarding</span><span className="v6-ramp-p">63%</span></div><div className="v6-bar"><div className="v6-fill" /></div></div></div></div></section>

          <section className="v6-section"><div className="v6-hl"><div className="v6-ba"><div className="v6-ba-col"><span className="v6-ba-label v6-ba-red">Without a system</span><div className="v6-ba-item">📋 Onboarding in a Google Doc nobody updates</div><div className="v6-ba-item">📝 Coaching notes scattered across 3 tools</div><div className="v6-ba-item">📊 No way to prove ramp time improved</div><div className="v6-ba-item">💬 Requests via Slack, email, hallway</div><div className="v6-ba-item">😓 Leadership asks for ROI. Awkward silence.</div></div><div className="v6-ba-arrow">→</div><div className="v6-ba-col"><span className="v6-ba-label v6-ba-green">With EnableOS</span><div className="v6-ba-item">✅ Onboarding tracked per rep with progress bars</div><div className="v6-ba-item">✅ AI-analyzed notes flag who needs coaching</div><div className="v6-ba-item">✅ Ramp dashboard shows exactly how fast reps ship</div><div className="v6-ba-item">✅ One intake queue, auto-prioritized</div><div className="v6-ba-item">✅ Real data for every leadership conversation</div></div></div></div></section>

          <section className="v6-section" id="how-it-works"><div className="v6-hl"><span className="v6-eyebrow">How it works</span><h2 className="v6-h2">Four steps. <em>Zero blank pages.</em></h2><div className="v6-steps">{[{icon:'01',t:'Discovery call',d:'30 minutes to understand the sales process, team, and where things break.'},{icon:'02',t:'Audit & design',d:'Gaps get mapped. Onboarding, coaching, and content systems get designed.'},{icon:'🛠',t:'Workspace built',d:'The EnableOS workspace gets loaded — configured to the team, not empty.'},{icon:'🚀',t:'Log in. It\'s ready.',d:'Launch call, full walkthrough, and ongoing check-ins as the team grows.'}].map((s,i)=>(<div key={i} className="v6-step-card"><div className="v6-step-num">{String(i+1).padStart(2,'0')}</div><div className="v6-step-icon">{s.icon}</div><h3>{s.t}</h3><p>{s.d}</p></div>))}</div><div className="v6-timeline"><span>Week 0</span><div className="v6-tl" /><span>Weeks 1–4</span><div className="v6-tl" /><span>Week 4–5</span><div className="v6-tl" /><span>Ongoing</span></div></div></section>

          <section className="v6-section" id="who-its-for"><div className="v6-hl"><span className="v6-eyebrow">Which one sounds like you?</span><h2 className="v6-h2">Three starting points. <em>One system.</em></h2><div className="v6-models">{[{tag:'Ground Zero',c:1,h:'Just hired first reps. No playbooks, no process.',desc:'Sales process lives in someone\'s head. Onboarding is "shadow someone for a week."',what:'Tribal knowledge gets extracted. A full system gets designed and delivered as a ready-to-use workspace.'},{tag:'Scattered but Scaling',c:2,h:'Team and data exist — nobody connecting the dots.',desc:'Gong recordings nobody watches. A 40-page playbook nobody reads.',what:'Existing content gets audited, restructured, and migrated into one workspace that connects everything.'},{tag:'Stretched Too Thin',c:3,h:'Enablement person doing great work — buried across 10 tools.',desc:'The work is happening. It\'s just invisible. No system to prove impact.',what:'Workflows get mapped with the enablement person, then migrated into one visible, trackable workspace.'}].map((m,i)=>(<div key={i} className="v6-model"><div className={`v6-model-tag v6-mt-${m.c}`}>{m.tag}</div><h3>{m.h}</h3><p className="v6-md">{m.desc}</p><p className="v6-mw">{m.what}</p><a href="https://calendly.com/enableos-hq/30min" target="_blank" rel="noreferrer" className="v6-mc">Book a call →</a></div>))}</div></div></section>

          <section className="v6-section" id="platform"><div className="v6-hl"><span className="v6-eyebrow">What&apos;s inside</span><h2 className="v6-h2">Not empty. <em>Never empty.</em></h2><div className="v6-pw"><div className="v6-pg" /><div className="v6-preview"><div className="v6-ps"><div className="v6-pl"><svg width="18" height="18" viewBox="0 0 24 24" fill="none"><rect x="2" y="4" width="14" height="3" rx="1.5" fill="#BDA9FF" opacity="0.5"/><rect x="4" y="9" width="14" height="4" rx="1.5" fill="#9B7EFF" opacity="0.75"/><rect x="6" y="15" width="14" height="5" rx="1.5" fill="#7C5CFC"/></svg><span>EnableOS</span></div>{['Dashboard','Intake','Ramp','1:1 Notes','Collaterals','Pulse Checks','Sessions'].map((item,i)=>(<div key={item} className={`v6-pn ${i===0?'active':''}`}>{item}</div>))}</div><div className="v6-pm"><div className="v6-ph"><span className="v6-pt">Dashboard</span><span className="v6-pb">Live</span></div><div className="v6-pc">{[['Reps ramping','4'],['Open requests','7'],['Sessions','2']].map(([l,v],i)=>(<div key={i} className={`v6-pcard v6-pa-${i+1}`}><div className="v6-pcl">{l}</div><div className="v6-pcn">{v}</div></div>))}</div><div className="v6-pr">{[['Aisha · Wk 4','63%'],['Dev · Wk 2','35%'],['Priya · Wk 6','88%']].map(([n,w],i)=>(<div key={i} className="v6-prr"><span>{n}</span><div className="v6-prb"><div className="v6-prf" style={{width:w}} /></div></div>))}</div></div></div></div></div></section>

          <section className="v6-section" id="pricing"><div className="v6-hl"><span className="v6-eyebrow">Engagement</span><h2 className="v6-h2">Not a subscription. <em>A partnership.</em></h2><p style={{fontSize:15,color:'var(--cm)',lineHeight:1.7,fontWeight:300,maxWidth:560,marginBottom:28}}>Every engagement includes a discovery call, a full audit, a configured workspace, and ongoing check-ins. Pricing depends on team size, complexity, and starting point — and costs a fraction of a full-time enablement hire.</p><div style={{textAlign:'center'}}><a href="https://calendly.com/enableos-hq/30min" target="_blank" rel="noreferrer" className="v6-btn-p">Book a free discovery call to discuss →</a></div></div></section>

          <section className="v6-section" id="founder"><div className="v6-hl"><div className="v6-founder"><div className="v6-fiw"><img src="/founder.jpg" alt="Vedika Agarwal" className="v6-fi" /></div><div className="v6-ft"><span className="v6-eyebrow">Who builds your workspace</span><h2 className="v6-h2" style={{fontSize:'34px'}}>Hi, I&apos;m Vedika.</h2><p className="v6-fb">Built enablement functions from scratch at two B2B SaaS companies. Designed onboarding programs that cut ramp time by 50%, created collaterals adopted within 24 hours, and coached 20+ reps across regions. Started as an SDR (191% quota) — so every system is built from the rep&apos;s perspective.</p><p className="v6-fb">EnableOS exists because every enablement person deserves better than 6 tools with no proof it matters.</p><div className="v6-fl"><a href="https://www.linkedin.com/in/vedikaagarwal00/" target="_blank" rel="noreferrer" className="v6-flink"><svg width="16" height="16" viewBox="0 0 24 24" fill="currentColor"><path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433a2.062 2.062 0 01-2.063-2.065 2.064 2.064 0 112.063 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z"/></svg>LinkedIn</a><a href="mailto:enableos.hq@gmail.com" className="v6-flink"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><rect x="2" y="4" width="20" height="16" rx="2"/><path d="M22 4L12 13 2 4"/></svg>enableos.hq@gmail.com</a></div></div></div></div></section>

          <section className="v6-section" id="faq"><div className="v6-hl"><span className="v6-eyebrow">Common questions</span><h2 className="v6-h2">Before you book.</h2><FAQ /></div></section>

          <section className="v6-section"><div className="v6-hl"><div className="v6-cta-content"><h2 className="v6-cta-h2">Your reps shouldn&apos;t have to <em>figure it out alone.</em></h2><p className="v6-cta-sub">30-minute discovery call. Free. No commitment.</p><a href="https://calendly.com/enableos-hq/30min" target="_blank" rel="noreferrer" className="v6-cta-big">Book a free discovery call →</a></div></div></section>
        </div>

        <footer className="v6-footer"><div className="v6-footer-inner"><div className="v6-footer-top"><div className="v6-footer-brand"><Logo /><p className="v6-footer-tag">Enablement consulting + a platform to run it.</p></div><div className="v6-footer-cols"><div className="v6-footer-col"><h4>Product</h4><a href="#how-it-works">How it works</a><a href="#who-its-for">Who it&apos;s for</a><a href="#faq">FAQ</a><a href="/roadmap">Roadmap</a></div><div className="v6-footer-col"><h4>Get started</h4><a href="/demo">Explore demo</a><a href="https://calendly.com/enableos-hq/30min" target="_blank" rel="noreferrer">Book a call</a><a href="/login">Log in</a></div><div className="v6-footer-col"><h4>Connect</h4><a href="mailto:enableos.hq@gmail.com">enableos.hq@gmail.com</a><a href="https://www.linkedin.com/in/vedikaagarwal00/" target="_blank" rel="noreferrer">LinkedIn</a></div></div></div><div className="v6-footer-bottom"><span>© 2026 EnableOS. Built in Bangalore.</span></div></div></footer>
      </div>
    </>
  );
}

const styles = `
@import url('https://fonts.googleapis.com/css2?family=Libre+Baskerville:ital,wght@0,400;0,700;1,400&family=Sora:wght@300;400;500;600;700&display=swap');
:root{--p:0}html{scroll-behavior:smooth}body{margin:0;font-family:'Sora',sans-serif;background:#1a1235;color:#F5F0FF;overflow-x:hidden;-webkit-font-smoothing:antialiased}*{box-sizing:border-box}a{text-decoration:none;color:inherit;cursor:pointer}
.v6-wrap{--bg-page:color-mix(in oklab,#1a1235,#FDFBFF calc(var(--p)*100%));--block:#1a1235;--cream:#F5F0FF;--cm:#A8A0C0;--cf:#6B6385;--accent:#7B6ED6;--as:rgba(123,110,214,0.1);--bl:rgba(245,240,255,0.08);background:var(--bg-page);color:var(--cream);min-height:100vh;position:relative;isolation:isolate}
.v6-bg{position:fixed;top:0;left:0;right:0;pointer-events:none;z-index:0;overflow:hidden;opacity:calc(1 - var(--p)*0.95);height:100vh}
.v6-aurora{position:absolute;top:0;left:-10%;right:-10%;height:800px;background:radial-gradient(ellipse at 30% 30%,rgba(123,110,214,0.28),transparent 55%),radial-gradient(ellipse at 70% 15%,rgba(200,120,180,0.12),transparent 60%);filter:blur(40px);animation:au 18s ease-in-out infinite}
@keyframes au{0%,100%{transform:translate(0,0)scale(1);opacity:.85}50%{transform:translate(40px,30px)scale(1.1);opacity:1}}
.v6-orb{position:absolute;border-radius:50%;filter:blur(70px)}.v6-orb-1{width:420px;height:420px;background:radial-gradient(circle,rgba(123,110,214,0.35),transparent 70%);top:-80px;right:-80px;animation:o1 20s ease-in-out infinite}.v6-orb-2{width:360px;height:360px;background:radial-gradient(circle,rgba(76,50,180,0.4),transparent 70%);top:60vh;left:-100px;animation:o2 24s ease-in-out infinite}.v6-orb-3{width:280px;height:280px;background:radial-gradient(circle,rgba(200,140,180,0.14),transparent 70%);top:30vh;right:10%;animation:o3 26s ease-in-out infinite}
@keyframes o1{0%,100%{transform:translate(0,0)scale(1)}50%{transform:translate(-50px,60px)scale(1.15)}}@keyframes o2{0%,100%{transform:translate(0,0)scale(1)}50%{transform:translate(60px,-40px)scale(1.1)}}@keyframes o3{0%,100%{transform:translate(0,0)}50%{transform:translate(40px,-30px)}}
.v6-frag{position:absolute;pointer-events:none}
.v6-frag-pri-1{top:14vh;left:7%;background:linear-gradient(135deg,rgba(123,110,214,0.3),rgba(100,80,200,0.3));color:rgba(255,255,255,0.65);padding:6px 14px;border-radius:8px;font-size:13px;font-weight:700;opacity:.5;transform:rotate(-8deg);animation:fd1 22s ease-in-out infinite}
.v6-frag-pri-2{top:32vh;left:3%;background:linear-gradient(135deg,rgba(123,110,214,0.18),rgba(100,80,200,0.18));color:rgba(255,255,255,0.4);padding:4px 10px;border-radius:6px;font-size:11px;font-weight:600;opacity:.35;filter:blur(1.5px);transform:rotate(6deg);animation:fd2 28s ease-in-out infinite}
.v6-frag-pri-3{top:56vh;right:5%;background:linear-gradient(135deg,rgba(200,120,180,0.18),rgba(123,110,214,0.18));color:rgba(255,255,255,0.45);padding:5px 12px;border-radius:7px;font-size:12px;font-weight:700;opacity:.4;filter:blur(1px);transform:rotate(-4deg);animation:fd3 26s ease-in-out infinite}
.v6-frag-ai-1{top:26vh;left:13%;background:rgba(123,110,214,0.18);color:rgba(245,240,255,0.8);padding:5px 12px;border-radius:14px;font-size:11px;font-weight:600;opacity:.5;animation:fd2 24s ease-in-out infinite}
.v6-frag-dot{position:absolute;width:8px;height:8px;border-radius:50%;background:rgba(123,110,214,0.5);box-shadow:0 0 12px rgba(123,110,214,0.7)}
.v6-frag-dot-1{top:20vh;left:28%;animation:fp 3s ease-in-out infinite,fd2 35s ease-in-out infinite}.v6-frag-dot-2{top:70vh;left:32%;animation:fp 2.4s ease-in-out infinite 1s,fd3 33s ease-in-out infinite}.v6-frag-dot-3{top:45vh;right:22%;animation:fp 2.8s ease-in-out infinite .5s,fd1 36s ease-in-out infinite}
@keyframes fp{0%,100%{opacity:.4;transform:scale(1)}50%{opacity:1;transform:scale(1.4)}}
@keyframes fd1{0%,100%{transform:translate(0,0)rotate(-8deg)}50%{transform:translate(30px,-20px)rotate(-4deg)}}
@keyframes fd2{0%,100%{transform:translate(0,0)rotate(6deg)}50%{transform:translate(-25px,25px)rotate(2deg)}}
@keyframes fd3{0%,100%{transform:translate(0,0)rotate(-4deg)}50%{transform:translate(35px,15px)rotate(0deg)}}
.v6-dots{position:absolute;inset:0;background-image:radial-gradient(rgba(123,110,214,0.18) .6px,transparent .6px);background-size:28px 28px;opacity:.35}
.v6-content{position:relative;z-index:1;padding:0 48px 48px;max-width:1280px;margin:0 auto}
.v6-nav{display:flex;justify-content:space-between;align-items:center;padding:14px 48px;border-bottom:1px solid var(--bl);margin:0 -48px 60px;position:sticky;top:0;z-index:10;backdrop-filter:blur(12px);background:color-mix(in oklab,rgba(26,18,53,.8),rgba(253,251,255,.8) calc(var(--p)*100%))}
.v6-logo{display:inline-flex;align-items:center;height:44px;color:color-mix(in oklab,#fff,#1a1235 calc(var(--p)*100%));--logo-os:color-mix(in oklab,#BDA9FF,#7C5CFC calc(var(--p)*100%))}.v6-logo-svg{height:100%;width:auto;display:block;overflow:visible}.v6-logo-os{fill:var(--logo-os)}
.v6-navlinks{display:flex;gap:26px;align-items:center;font-size:13px;color:color-mix(in oklab,var(--cm),#4a4162 calc(var(--p)*100%))}.v6-cta-nav{background:color-mix(in oklab,var(--cream),#1a1235 calc(var(--p)*100%));color:color-mix(in oklab,#1a1235,var(--cream) calc(var(--p)*100%));padding:9px 18px;border-radius:8px;font-size:13px;font-weight:600}.v6-demo-link{font-weight:600;color:color-mix(in oklab,#BDA9FF,#7C5CFC calc(var(--p)*100%));border-bottom:1px solid transparent;transition:border-color .2s}.v6-demo-link:hover{border-bottom-color:currentColor}
.v6-section{padding-bottom:68px;scroll-margin-top:90px}.v6-hl{position:relative;padding:44px 40px;border-radius:20px;z-index:1;isolation:isolate}.v6-hl::before{content:'';position:absolute;inset:0;background:var(--block);opacity:var(--p);border-radius:inherit;z-index:-1;box-shadow:0 24px 48px -16px rgba(0,0,0,calc(var(--p)*.25))}
.v6-hero{display:grid;grid-template-columns:1fr 1fr;gap:52px;align-items:center;min-height:70vh;padding-top:12px}
.v6-eyebrow{display:inline-flex;align-items:center;gap:10px;font-size:11px;font-weight:500;letter-spacing:2.2px;text-transform:uppercase;color:var(--cm);margin-bottom:20px}.v6-eyebrow::before{content:'';width:24px;height:1px;background:var(--accent)}
.v6-h1{font-family:'Libre Baskerville',serif;font-size:48px;line-height:1.12;margin:0 0 20px;font-weight:400;color:var(--cream);letter-spacing:-1px}.v6-h1 em{font-style:italic;color:#FFFAF0}
.v6-sub{font-size:15px;color:var(--cm);margin-bottom:28px;line-height:1.7;max-width:460px;font-weight:300}
.v6-btns{display:flex;gap:14px;align-items:center;margin-bottom:16px}.v6-btn-p{background:#F5F0FF;color:#1a1235;padding:14px 24px;border-radius:10px;font-size:14px;font-weight:600;transition:transform .2s;display:inline-block}.v6-btn-p:hover{transform:translateY(-2px)}.v6-btn-s{color:#F5F0FF;padding:14px 8px;font-size:14px;font-weight:500;border-bottom:1px solid rgba(245,240,255,.25)}
.v6-hero-proof{display:flex;gap:6px;font-size:11px;color:var(--cf);font-weight:300;flex-wrap:wrap}.v6-sep{color:var(--accent);opacity:.5}
.v6-dash-wrap{position:relative}.v6-dash-glow{position:absolute;inset:-30px;background:radial-gradient(ellipse at center,rgba(123,110,214,.2),transparent 65%);filter:blur(40px);animation:br 6s ease-in-out infinite;z-index:0}@keyframes br{0%,100%{opacity:.35;transform:scale(.96)}50%{opacity:.7;transform:scale(1.04)}}
.v6-dash{position:relative;background:#FDFBFF;color:#1a1235;border-radius:14px;padding:16px;box-shadow:0 28px 70px -18px rgba(0,0,0,.4);z-index:1}
.v6-dh{display:flex;justify-content:space-between;align-items:center;margin-bottom:10px;padding-bottom:9px;border-bottom:1px solid #F0ECFF;font-size:12px;font-weight:600}.v6-dh-live{display:inline-flex;align-items:center;gap:4px;font-size:10px;color:#6BCB77}.v6-dh-live-dot{width:6px;height:6px;border-radius:50%;background:#6BCB77;animation:lp 1.5s ease-in-out infinite}@keyframes lp{0%,100%{box-shadow:0 0 0 0 rgba(107,203,119,.5)}50%{box-shadow:0 0 0 4px rgba(107,203,119,0)}}
.v6-intake{background:#FDFBFF;border:1px solid #E2DCF0;border-radius:9px;padding:11px;margin-bottom:7px;position:relative}.v6-intake::before{content:'';position:absolute;left:0;top:0;bottom:0;width:3px;background:var(--accent);border-radius:9px 0 0 9px}.v6-int-top{display:flex;justify-content:space-between;align-items:flex-start}.v6-int-title{font-size:12px;font-weight:600;color:#1a1235}.v6-int-meta{font-size:10px;color:#8b82a0;margin-top:2px}.v6-pri{background:#1a1235;color:#F5F0FF;padding:3px 9px;border-radius:5px;font-size:10px;font-weight:700}
.v6-note{background:#FDFBFF;border:1px solid #E2DCF0;border-radius:9px;padding:11px;margin-bottom:7px}.v6-note-rep{font-size:11px;font-weight:600;color:#1a1235;margin-bottom:3px}.v6-note-txt{font-size:10px;color:#4a4162;font-style:italic;margin-bottom:5px;line-height:1.5}.v6-ai{display:inline-flex;gap:3px;padding:3px 9px;border-radius:10px;font-size:9px;font-weight:600;background:linear-gradient(135deg,#FFF4E5,#FFE8D6);color:#B85C00}
.v6-ramp{background:#FDFBFF;border:1px solid #E2DCF0;border-radius:9px;padding:11px}.v6-ramp-top{display:flex;justify-content:space-between;align-items:center;margin-bottom:5px;font-size:11px;font-weight:600;color:#1a1235}.v6-ramp-p{font-family:'Libre Baskerville',serif;font-size:13px;font-weight:700}.v6-bar{background:#F0ECFF;height:5px;border-radius:3px;overflow:hidden}.v6-fill{background:linear-gradient(90deg,#7B6ED6,#9B8FE0);height:100%;width:63%;border-radius:3px}
.v6-ba{display:grid;grid-template-columns:1fr auto 1fr;gap:24px;align-items:stretch}.v6-ba-col{display:flex;flex-direction:column;gap:8px}.v6-ba-label{display:inline-block;font-size:10px;font-weight:700;letter-spacing:1.5px;text-transform:uppercase;padding:5px 14px;border-radius:100px;margin-bottom:4px;width:fit-content}.v6-ba-red{background:rgba(220,38,38,.12);color:#fca5a5}.v6-ba-green{background:rgba(107,203,119,.12);color:#8FDD96}.v6-ba-item{font-size:14px;color:var(--cm);line-height:1.45;font-weight:300;padding:7px 0;border-bottom:1px solid var(--bl)}.v6-ba-arrow{font-size:28px;color:var(--accent);display:flex;align-items:center;opacity:.3}
.v6-h2{font-family:'Libre Baskerville',serif;font-size:42px;line-height:1.12;font-weight:400;color:var(--cream);letter-spacing:-.8px;max-width:680px;margin:0 0 28px}.v6-h2 em{font-style:italic;color:#FFFAF0}
.v6-steps{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin-top:24px}.v6-step-card{background:var(--block);border:1px solid var(--bl);border-radius:14px;padding:22px 18px}.v6-step-num{display:none}.v6-step-icon{font-family:'Libre Baskerville',serif;font-size:28px;font-weight:700;color:var(--accent);margin-bottom:10px;opacity:.3}.v6-step-card h3{font-family:'Libre Baskerville',serif;font-size:16px;font-weight:700;margin:0 0 6px;color:var(--cream)}.v6-step-card p{font-size:13px;color:var(--cm);line-height:1.6;margin:0;font-weight:300}
.v6-timeline{display:flex;align-items:center;margin-top:22px;padding-top:16px;border-top:1px solid var(--bl);font-size:12px;color:var(--cf);font-weight:500}.v6-tl{flex:1;height:1px;background:var(--bl);margin:0 12px}
.v6-models{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin-top:20px}.v6-model{background:var(--block);border:1px solid var(--bl);border-radius:16px;padding:24px 20px;display:flex;flex-direction:column}.v6-model-tag{display:inline-block;font-size:10px;letter-spacing:1.5px;text-transform:uppercase;font-weight:700;padding:5px 12px;border-radius:100px;margin-bottom:12px;width:fit-content}.v6-mt-1{background:rgba(255,140,66,.12);color:#FFB87A}.v6-mt-2{background:rgba(255,196,0,.1);color:#FFD466}.v6-mt-3{background:rgba(107,203,119,.1);color:#8FDD96}.v6-model h3{font-family:'Libre Baskerville',serif;font-size:16px;font-weight:400;line-height:1.35;margin:0 0 8px;color:var(--cream)}.v6-md{font-size:13px;color:var(--cf);line-height:1.5;margin:0 0 10px;font-weight:300}.v6-mw{font-size:13px;color:var(--cm);line-height:1.6;margin:0 0 12px;font-weight:300;border-top:1px solid var(--bl);padding-top:10px;flex-grow:1}.v6-mc{display:inline-block;color:var(--cm);font-size:13px;font-weight:600;border-bottom:1px solid rgba(168,160,192,.25);padding-bottom:2px}.v6-mc:hover{color:var(--cream)}
.v6-pw{position:relative;margin-top:8px}.v6-pg{position:absolute;inset:-40px;background:radial-gradient(ellipse at center,rgba(123,110,214,.1),transparent 65%);filter:blur(50px);z-index:0}
.v6-preview{position:relative;z-index:1;background:#FDFBFF;border-radius:14px;display:grid;grid-template-columns:155px 1fr;overflow:hidden;box-shadow:0 28px 70px -18px rgba(0,0,0,.4);min-height:300px}
.v6-ps{background:#1a1235;padding:14px 10px;display:flex;flex-direction:column;gap:2px}.v6-pl{display:flex;align-items:center;gap:6px;color:#F5F0FF;font-size:11px;font-weight:700;font-family:'Libre Baskerville',serif;margin-bottom:12px;padding-bottom:10px;border-bottom:1px solid rgba(255,255,255,.05)}.v6-pn{font-size:10px;color:rgba(255,255,255,.35);padding:6px 8px;border-radius:5px}.v6-pn.active{background:rgba(123,110,214,.18);color:#F5F0FF;font-weight:600}
.v6-pm{padding:16px 18px;color:#1a1235}.v6-ph{display:flex;justify-content:space-between;align-items:center;margin-bottom:12px}.v6-pt{font-family:'Libre Baskerville',serif;font-size:14px;font-weight:700}.v6-pb{font-size:9px;color:#6BCB77;font-weight:600;background:rgba(107,203,119,.1);padding:3px 8px;border-radius:100px}
.v6-pc{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-bottom:10px}.v6-pcard{background:#F8F5FF;border:1px solid #E2DCF0;border-radius:9px;padding:11px}.v6-pcl{font-size:8px;color:#8b82a0;text-transform:uppercase;letter-spacing:.6px;font-weight:600;margin-bottom:2px}.v6-pcn{font-family:'Libre Baskerville',serif;font-size:22px;font-weight:700;color:#1a1235}
.v6-pr{background:#F8F5FF;border:1px solid #E2DCF0;border-radius:9px;padding:12px}.v6-prr{margin-bottom:8px}.v6-prr:last-child{margin-bottom:0}.v6-prr span{font-size:10px;color:#4a4162;font-weight:500;display:block;margin-bottom:3px}.v6-prb{background:#F0ECFF;height:4px;border-radius:2px;overflow:hidden}.v6-prf{background:linear-gradient(90deg,#7B6ED6,#9B8FE0);height:100%;border-radius:2px}
.v6-pa-1{animation:cf .8s ease both .2s}.v6-pa-2{animation:cf .8s ease both .4s}.v6-pa-3{animation:cf .8s ease both .6s}@keyframes cf{from{opacity:0;transform:translateY(8px)}to{opacity:1;transform:translateY(0)}}
.v6-pricing{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin-bottom:16px}.v6-price-card{background:var(--block);border:1px solid var(--bl);border-radius:14px;padding:22px}.v6-price-label{font-size:10px;font-weight:700;letter-spacing:1.2px;text-transform:uppercase;color:var(--cf);margin-bottom:8px}.v6-price-range{font-family:'Libre Baskerville',serif;font-size:26px;font-weight:700;color:var(--cream);margin-bottom:6px;letter-spacing:-.5px}.v6-price-card p{font-size:13px;color:var(--cm);line-height:1.5;margin:0;font-weight:300}.v6-price-note{font-size:13px;color:var(--cf);text-align:center}
.v6-founder{display:grid;grid-template-columns:auto 1fr;gap:36px;align-items:center}.v6-fiw{width:180px;height:180px}.v6-fi{width:180px;height:180px;border-radius:14px;object-fit:cover;box-shadow:0 14px 40px -10px rgba(0,0,0,.3)}.v6-ft .v6-eyebrow{margin-bottom:10px}.v6-ft .v6-h2{margin-bottom:12px}.v6-fb{font-size:14px;color:var(--cm);line-height:1.65;margin:0 0 10px;font-weight:300;max-width:480px}.v6-fl{display:flex;gap:14px;margin-top:16px}.v6-flink{display:inline-flex;align-items:center;gap:6px;font-size:13px;color:var(--cm);font-weight:500;border:1px solid var(--bl);padding:7px 13px;border-radius:7px}.v6-flink:hover{background:var(--as);color:var(--cream)}
.v6-faq-list{margin-top:4px}.v6-faq-item{border-bottom:1px solid var(--bl);cursor:pointer}.v6-faq-q{display:flex;justify-content:space-between;align-items:center;padding:16px 0;gap:14px}.v6-faq-q span:first-child{font-size:15px;font-weight:500;color:var(--cream);line-height:1.4}.v6-faq-toggle{width:22px;height:22px;border-radius:50%;background:var(--as);color:var(--cm);display:flex;align-items:center;justify-content:center;font-size:15px;flex-shrink:0}.v6-faq-a{font-size:14px;color:var(--cm);line-height:1.7;padding:0 0 16px;margin:0;font-weight:300;max-width:600px}
.v6-cta-content{text-align:center;padding:12px 0}.v6-cta-h2{font-family:'Libre Baskerville',serif;font-size:42px;line-height:1.12;font-weight:400;color:var(--cream);letter-spacing:-.8px;max-width:560px;margin:0 auto 16px}.v6-cta-h2 em{font-style:italic}.v6-cta-sub{font-size:15px;color:var(--cm);margin-bottom:24px;max-width:400px;margin-left:auto;margin-right:auto;line-height:1.6;font-weight:300}.v6-cta-big{display:inline-block;background:#F5F0FF;color:#1a1235;padding:15px 32px;border-radius:10px;font-size:15px;font-weight:600;transition:transform .2s;box-shadow:0 14px 36px -10px rgba(0,0,0,.25)}.v6-cta-big:hover{transform:translateY(-2px)}
.v6-scroll-hint{position:fixed;bottom:24px;left:50%;transform:translateX(-50%);font-size:10px;letter-spacing:2px;text-transform:uppercase;color:rgba(245,240,255,.4);pointer-events:none;opacity:calc(1 - var(--p)*5);animation:hb 2s ease-in-out infinite;z-index:20}@keyframes hb{0%,100%{transform:translateX(-50%)translateY(0)}50%{transform:translateX(-50%)translateY(4px)}}
.v6-footer{position:relative;z-index:1;padding:48px 48px 24px;border-top:1px solid var(--bl);background:color-mix(in oklab,rgba(26,18,53,.85),rgba(253,251,255,.85) calc(var(--p)*100%));backdrop-filter:blur(12px)}.v6-footer-inner{max-width:1280px;margin:0 auto}.v6-footer-top{display:grid;grid-template-columns:1.4fr 2fr;gap:48px;padding-bottom:28px;border-bottom:1px solid var(--bl)}.v6-footer-brand .v6-logo{margin-bottom:12px}.v6-footer-tag{font-size:14px;color:color-mix(in oklab,var(--cm),#4a4162 calc(var(--p)*100%));line-height:1.6;max-width:280px;margin:0;font-weight:300}.v6-footer-cols{display:grid;grid-template-columns:repeat(3,1fr);gap:24px}.v6-footer-col h4{font-size:10px;letter-spacing:1.5px;text-transform:uppercase;color:color-mix(in oklab,var(--cf),#4a4162 calc(var(--p)*100%));font-weight:600;margin:0 0 12px}.v6-footer-col a{display:block;font-size:14px;color:color-mix(in oklab,var(--cm),#4a4162 calc(var(--p)*100%));padding:4px 0;font-weight:300}.v6-footer-col a:hover{color:color-mix(in oklab,var(--cream),#1a1235 calc(var(--p)*100%))}.v6-footer-bottom{padding-top:20px;text-align:center;font-size:12px;color:color-mix(in oklab,var(--cf),#4a4162 calc(var(--p)*100%));font-weight:300}
@media(max-width:768px){.v6-content{padding:0 22px 24px}.v6-nav{padding:12px 22px;margin:0 -22px 36px}.v6-navlinks a:not(.v6-cta-nav){display:none}.v6-navlinks{gap:14px}.v6-logo{height:36px}.v6-hero{grid-template-columns:1fr;gap:32px;min-height:auto;padding-top:8px}.v6-h1{font-size:32px}.v6-h2{font-size:26px}.v6-sub{font-size:14px}.v6-ba{grid-template-columns:1fr;gap:16px}.v6-ba-arrow{display:none}.v6-steps{grid-template-columns:1fr 1fr;gap:10px}.v6-timeline{flex-wrap:wrap;gap:6px}.v6-tl{display:none}.v6-models{grid-template-columns:1fr;gap:10px}.v6-preview{grid-template-columns:1fr}.v6-ps{display:none}.v6-pc{grid-template-columns:1fr}.v6-pricing{grid-template-columns:1fr;gap:10px}.v6-founder{grid-template-columns:1fr;text-align:center;gap:20px}.v6-fiw{margin:0 auto;width:130px;height:130px}.v6-fi{width:130px;height:130px}.v6-fb{max-width:100%}.v6-fl{justify-content:center}.v6-hl{padding:26px 20px}.v6-cta-h2{font-size:28px}.v6-footer{padding:36px 22px 20px}.v6-footer-top{grid-template-columns:1fr;gap:24px;padding-bottom:20px}.v6-footer-cols{grid-template-columns:1fr 1fr;gap:16px}.v6-section{scroll-margin-top:72px}}
`;
